import { ValidationError } from "../errors";
import {
  createEmailAddress,
  type EmailAddress,
} from "../value-objects/email-address";
import {
  compareIsoDates,
  createIsoDate,
  type IsoDate,
} from "../value-objects/iso-date";
import type {
  CalendarEventId,
  CalendarId,
  EventLinkId,
} from "../value-objects/ids";
import type { RecurrenceRule } from "../value-objects/recurrence";
import type { TimeZoneId } from "../value-objects/time-zone";

/** A timed event is an instant pair plus the zone its wall-clock times were
 * authored in -- the zone is needed for recurrence, since "every Monday at
 * 09:00" means 09:00 local, not a fixed UTC offset. An all-day event has no
 * zone at all; see `IsoDate`. */
export type EventTime =
  | {
      readonly kind: "TIMED";
      readonly startsAt: number;
      readonly endsAt: number;
      readonly timeZone: TimeZoneId;
    }
  | {
      readonly kind: "ALL_DAY";
      readonly startDate: IsoDate;
      readonly endDateExclusive: IsoDate;
    };

/** Identifies one generated occurrence of a series: epoch ms for a timed
 * event, an `IsoDate` for an all-day one. Used by `EXDATE` entries and by
 * `RECURRENCE-ID` override linkage. */
export type OccurrenceStart = number | IsoDate;

export interface EventLink {
  readonly id: EventLinkId;
  readonly url: string;
  readonly title: string | null;
  readonly position: number;
}

export interface EventOverrideRef {
  readonly parentEventId: CalendarEventId;
  readonly recurrenceInstanceStart: OccurrenceStart;
}

export interface CalendarEvent {
  readonly id: CalendarEventId;
  readonly calendarId: CalendarId;
  /** iCalendar `UID`. Generated by the application layer for local events;
   * preserved verbatim for events imported over CalDAV, since it is the
   * only stable identity a remote server and mailcal share. */
  readonly uid: string;
  readonly title: string;
  readonly description: string | null;
  readonly location: string | null;
  readonly time: EventTime;
  readonly recurrence: RecurrenceRule | null;
  readonly exdates: readonly OccurrenceStart[];
  readonly overrideOf: EventOverrideRef | null;
  /** Plain addresses. Deliberately carry no status of any kind: mailcal does
   * not do RSVP, so there is nowhere for accept/decline state to hide. */
  readonly mentions: readonly EmailAddress[];
  readonly links: readonly EventLink[];
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface EventLinkInput {
  readonly id: EventLinkId;
  readonly url: string;
  readonly title?: string | null;
  readonly position?: number;
}

export interface CreateCalendarEventInput {
  readonly id: CalendarEventId;
  readonly calendarId: CalendarId;
  readonly uid: string;
  readonly title: string;
  readonly description?: string | null;
  readonly location?: string | null;
  readonly time: EventTime;
  readonly recurrence?: RecurrenceRule | null;
  readonly exdates?: readonly OccurrenceStart[];
  readonly overrideOf?: EventOverrideRef | null;
  readonly mentions?: readonly string[];
  readonly links?: readonly EventLinkInput[];
  readonly createdAt: string;
  readonly updatedAt?: string;
}

export const MAX_EVENT_TITLE_LENGTH = 500;
export const MAX_EVENT_DESCRIPTION_LENGTH = 20_000;
export const MAX_EVENT_LOCATION_LENGTH = 1000;
export const MAX_EVENT_LINK_URL_LENGTH = 2048;
export const MAX_EVENT_LINKS = 50;
export const MAX_EVENT_MENTIONS = 200;

function validateEventTime(time: EventTime): EventTime {
  if (time.kind === "TIMED") {
    if (!Number.isFinite(time.startsAt) || !Number.isFinite(time.endsAt)) {
      throw new ValidationError(
        "event start and end must be valid timestamps",
        "time",
      );
    }
    if (time.endsAt <= time.startsAt) {
      throw new ValidationError("event end must be after its start", "endsAt");
    }
    return time;
  }
  const startDate = createIsoDate(time.startDate, "startDate");
  const endDateExclusive = createIsoDate(
    time.endDateExclusive,
    "endDateExclusive",
  );
  if (compareIsoDates(endDateExclusive, startDate) <= 0) {
    throw new ValidationError(
      "all-day event endDateExclusive must be after startDate",
      "endDateExclusive",
    );
  }
  return { kind: "ALL_DAY", startDate, endDateExclusive };
}

/** Only absolute `http(s)` URLs: a `javascript:` or `data:` link stored here
 * would be rendered as a clickable anchor by the web client. */
function validateLinkUrl(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed.length > MAX_EVENT_LINK_URL_LENGTH) {
    throw new ValidationError(
      `event link url must be between 1 and ${MAX_EVENT_LINK_URL_LENGTH} characters`,
      "url",
    );
  }
  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    throw new ValidationError("event link url must be absolute", "url");
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new ValidationError("event link url must use http or https", "url");
  }
  return url.toString();
}

function normalizeLinks(
  links: readonly EventLinkInput[],
): readonly EventLink[] {
  if (links.length > MAX_EVENT_LINKS) {
    throw new ValidationError(
      `an event may carry at most ${MAX_EVENT_LINKS} links`,
      "links",
    );
  }
  return links.map((link, index) => {
    const title = link.title?.trim() ?? "";
    return {
      id: link.id,
      url: validateLinkUrl(link.url),
      title: title.length === 0 ? null : title,
      // Positions are always renumbered from the array order, so a client
      // that reorders links does not have to compute them.
      position: link.position ?? index,
    };
  });
}

/** Normalizes, validates and de-duplicates mention addresses. Order of
 * first appearance is preserved so a client's list does not shuffle. */
function normalizeMentions(
  mentions: readonly string[],
): readonly EmailAddress[] {
  if (mentions.length > MAX_EVENT_MENTIONS) {
    throw new ValidationError(
      `an event may carry at most ${MAX_EVENT_MENTIONS} mentions`,
      "mentions",
    );
  }
  const seen = new Set<string>();
  const result: EmailAddress[] = [];
  for (const raw of mentions) {
    const address = createEmailAddress(raw, "mentions");
    if (seen.has(address)) {
      continue;
    }
    seen.add(address);
    result.push(address);
  }
  return result;
}

function normalizeExdates(
  exdates: readonly OccurrenceStart[],
  time: EventTime,
): readonly OccurrenceStart[] {
  const seen = new Set<OccurrenceStart>();
  const result: OccurrenceStart[] = [];
  for (const entry of exdates) {
    if (time.kind === "TIMED") {
      if (typeof entry !== "number" || !Number.isFinite(entry)) {
        throw new ValidationError(
          "timed event exdates must be timestamps",
          "exdates",
        );
      }
    } else if (typeof entry !== "string") {
      throw new ValidationError(
        "all-day event exdates must be YYYY-MM-DD dates",
        "exdates",
      );
    } else {
      createIsoDate(entry, "exdates");
    }
    if (seen.has(entry)) {
      continue;
    }
    seen.add(entry);
    result.push(entry);
  }
  return result.sort((left, right) =>
    typeof left === "number" && typeof right === "number"
      ? left - right
      : String(left).localeCompare(String(right)),
  );
}

function requireText(value: string, field: string, maxLength: number): string {
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    throw new ValidationError(`event ${field} must not be empty`, field);
  }
  if (trimmed.length > maxLength) {
    throw new ValidationError(
      `event ${field} must be at most ${maxLength} characters`,
      field,
    );
  }
  return trimmed;
}

function optionalText(
  value: string | null | undefined,
  field: string,
  maxLength: number,
): string | null {
  const trimmed = value?.trim() ?? "";
  if (trimmed.length === 0) {
    return null;
  }
  if (trimmed.length > maxLength) {
    throw new ValidationError(
      `event ${field} must be at most ${maxLength} characters`,
      field,
    );
  }
  return trimmed;
}

export function createCalendarEvent(
  input: CreateCalendarEventInput,
): CalendarEvent {
  const time = validateEventTime(input.time);
  const recurrence = input.recurrence ?? null;
  const overrideOf = input.overrideOf ?? null;
  // A row is either a series master (which may carry a rule) or a single
  // overridden instance of one. A row that is both would make "which rule
  // governs this instance" ambiguous, and CalDAV has no way to express it.
  if (overrideOf !== null && recurrence !== null) {
    throw new ValidationError(
      "an override event must not carry its own recurrence rule",
      "recurrence",
    );
  }
  if (overrideOf !== null) {
    const instanceStart = overrideOf.recurrenceInstanceStart;
    const expectsDate = time.kind === "ALL_DAY";
    if (expectsDate && typeof instanceStart !== "string") {
      throw new ValidationError(
        "all-day override recurrenceInstanceStart must be a YYYY-MM-DD date",
        "overrideOf",
      );
    }
    if (!expectsDate && typeof instanceStart !== "number") {
      throw new ValidationError(
        "timed override recurrenceInstanceStart must be a timestamp",
        "overrideOf",
      );
    }
  }
  const uid = requireText(input.uid, "uid", 512);

  return {
    id: input.id,
    calendarId: input.calendarId,
    uid,
    title: requireText(input.title, "title", MAX_EVENT_TITLE_LENGTH),
    description: optionalText(
      input.description,
      "description",
      MAX_EVENT_DESCRIPTION_LENGTH,
    ),
    location: optionalText(
      input.location,
      "location",
      MAX_EVENT_LOCATION_LENGTH,
    ),
    time,
    recurrence,
    exdates: normalizeExdates(input.exdates ?? [], time),
    overrideOf,
    mentions: normalizeMentions(input.mentions ?? []),
    links: normalizeLinks(input.links ?? []),
    createdAt: input.createdAt,
    updatedAt: input.updatedAt ?? input.createdAt,
  };
}

/** UTC bounds used for the denormalized `range_*_utc` query columns and for
 * in-memory overlap checks. An all-day event's bounds are midnight UTC of
 * its first and (exclusive) last day. */
export function eventTimeBoundsUtc(time: EventTime): {
  readonly startUtc: number;
  readonly endUtc: number;
} {
  if (time.kind === "TIMED") {
    return { startUtc: time.startsAt, endUtc: time.endsAt };
  }
  return {
    startUtc: Date.parse(`${time.startDate}T00:00:00.000Z`),
    endUtc: Date.parse(`${time.endDateExclusive}T00:00:00.000Z`),
  };
}

export function isRecurringMaster(event: CalendarEvent): boolean {
  return event.recurrence !== null;
}

export function isOverrideEvent(event: CalendarEvent): boolean {
  return event.overrideOf !== null;
}
