import { ValidationError } from "../errors";
import {
  createEmailAddress,
  type EmailAddress,
} from "../value-objects/email-address";
import { createIsoDate } from "../value-objects/iso-date";
import type { AddressBookId, ContactId } from "../value-objects/ids";

/** A contact's email, phone or postal address. `label` is free text (1..40)
 * rather than an enum: iCloud round-trips arbitrary labels (`"work"`,
 * `"mum's house"`, ...) and an enum would drop whatever it does not
 * enumerate on the next sync. */
export interface ContactEmail {
  readonly address: EmailAddress;
  readonly label: string | null;
}

export interface ContactPhone {
  readonly number: string;
  readonly label: string | null;
}

export interface ContactPostalAddress {
  readonly formatted: string;
  readonly label: string | null;
}

export interface Contact {
  readonly id: ContactId;
  readonly addressBookId: AddressBookId;
  /** vCard `UID`. Generated by the application layer for local contacts;
   * preserved verbatim for contacts imported over CardDAV, since it is the
   * only stable identity a remote server and mailcal share -- mirrors
   * `CalendarEvent.uid`. */
  readonly uid: string;
  readonly displayName: string;
  readonly givenName: string | null;
  readonly familyName: string | null;
  readonly nickname: string | null;
  readonly organization: string | null;
  readonly title: string | null;
  readonly emails: readonly ContactEmail[];
  readonly phones: readonly ContactPhone[];
  readonly postalAddresses: readonly ContactPostalAddress[];
  readonly urls: readonly string[];
  readonly note: string | null;
  readonly birthday: string | null;
  /** Unsupported vCard properties (`PHOTO`, `X-*`, ungrouped `item1.`
   * properties, ...) carried verbatim so a round trip through mailcal never
   * strips what it does not model. Opaque to the domain: never parsed,
   * validated, or rendered raw by a client -- see the vCard codec design. */
  readonly extraVcardLines: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface ContactEmailInput {
  readonly address: string;
  readonly label?: string | null;
}

export interface ContactPhoneInput {
  readonly number: string;
  readonly label?: string | null;
}

export interface ContactPostalAddressInput {
  readonly formatted: string;
  readonly label?: string | null;
}

export interface CreateContactInput {
  readonly id: ContactId;
  readonly addressBookId: AddressBookId;
  readonly uid: string;
  readonly displayName: string;
  readonly givenName?: string | null;
  readonly familyName?: string | null;
  readonly nickname?: string | null;
  readonly organization?: string | null;
  readonly title?: string | null;
  readonly emails?: readonly ContactEmailInput[];
  readonly phones?: readonly ContactPhoneInput[];
  readonly postalAddresses?: readonly ContactPostalAddressInput[];
  readonly urls?: readonly string[];
  readonly note?: string | null;
  readonly birthday?: string | null;
  readonly extraVcardLines?: string | null;
  readonly createdAt: string;
  readonly updatedAt?: string;
}

export const MAX_CONTACT_UID_LENGTH = 512;
export const MAX_CONTACT_DISPLAY_NAME_LENGTH = 500;
export const MAX_CONTACT_NAME_PART_LENGTH = 500;
export const MAX_CONTACT_ORGANIZATION_LENGTH = 500;
export const MAX_CONTACT_TITLE_LENGTH = 500;
export const MAX_CONTACT_NOTE_LENGTH = 10_000;
export const MAX_CONTACT_PHONE_NUMBER_LENGTH = 50;
export const MAX_CONTACT_POSTAL_ADDRESS_LENGTH = 1000;
export const MAX_CONTACT_URL_LENGTH = 2048;
export const MAX_CONTACT_LABEL_LENGTH = 40;
// A hostile CardDAV server's vCard bomb must not become a megabyte row: the
// same cap applies to every child list (emails/phones/postalAddresses/urls).
export const MAX_CONTACT_LIST_LENGTH = 32;

function requireText(value: string, field: string, maxLength: number): string {
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    throw new ValidationError(`contact ${field} must not be empty`, field);
  }
  if (trimmed.length > maxLength) {
    throw new ValidationError(
      `contact ${field} must be at most ${maxLength} characters`,
      field,
    );
  }
  return trimmed;
}

function optionalText(
  value: string | null | undefined,
  field: string,
  maxLength: number,
): string | null {
  const trimmed = value?.trim() ?? "";
  if (trimmed.length === 0) {
    return null;
  }
  if (trimmed.length > maxLength) {
    throw new ValidationError(
      `contact ${field} must be at most ${maxLength} characters`,
      field,
    );
  }
  return trimmed;
}

/** Free-text label shared by emails/phones/postal addresses: 1..40 chars
 * once trimmed, or `null` for none. Never an enum -- see the module doc. */
function normalizeLabel(
  value: string | null | undefined,
  field: string,
): string | null {
  return optionalText(value, field, MAX_CONTACT_LABEL_LENGTH);
}

function requireListWithinCap<T>(list: readonly T[], field: string): void {
  if (list.length > MAX_CONTACT_LIST_LENGTH) {
    throw new ValidationError(
      `contact ${field} must contain at most ${MAX_CONTACT_LIST_LENGTH} entries`,
      field,
    );
  }
}

/** Normalizes each email through `createEmailAddress` and de-duplicates
 * case-insensitively -- `createEmailAddress` already lower-cases, so a plain
 * `Set` on the normalized value is enough. Order of first appearance is
 * preserved so a client's list does not shuffle. */
function normalizeEmails(
  emails: readonly ContactEmailInput[],
): readonly ContactEmail[] {
  requireListWithinCap(emails, "emails");
  const seen = new Set<EmailAddress>();
  const result: ContactEmail[] = [];
  for (const entry of emails) {
    const address = createEmailAddress(entry.address, "emails");
    if (seen.has(address)) {
      continue;
    }
    seen.add(address);
    result.push({
      address,
      label: normalizeLabel(entry.label, "emails.label"),
    });
  }
  return result;
}

function normalizePhones(
  phones: readonly ContactPhoneInput[],
): readonly ContactPhone[] {
  requireListWithinCap(phones, "phones");
  return phones.map((entry) => ({
    number: requireText(
      entry.number,
      "phones.number",
      MAX_CONTACT_PHONE_NUMBER_LENGTH,
    ),
    label: normalizeLabel(entry.label, "phones.label"),
  }));
}

function normalizePostalAddresses(
  postalAddresses: readonly ContactPostalAddressInput[],
): readonly ContactPostalAddress[] {
  requireListWithinCap(postalAddresses, "postalAddresses");
  return postalAddresses.map((entry) => ({
    formatted: requireText(
      entry.formatted,
      "postalAddresses.formatted",
      MAX_CONTACT_POSTAL_ADDRESS_LENGTH,
    ),
    label: normalizeLabel(entry.label, "postalAddresses.label"),
  }));
}

/** Only absolute `http(s)` URLs, deduplicated -- mirrors
 * `calendar-event.ts`'s `EventLink` URL validation. A `javascript:` or
 * `data:` link stored here would be rendered as a clickable anchor by the
 * web client. */
function normalizeUrls(urls: readonly string[]): readonly string[] {
  requireListWithinCap(urls, "urls");
  const seen = new Set<string>();
  const result: string[] = [];
  for (const raw of urls) {
    const trimmed = raw.trim();
    if (trimmed.length === 0 || trimmed.length > MAX_CONTACT_URL_LENGTH) {
      throw new ValidationError(
        `contact url must be between 1 and ${MAX_CONTACT_URL_LENGTH} characters`,
        "urls",
      );
    }
    let url: URL;
    try {
      url = new URL(trimmed);
    } catch {
      throw new ValidationError("contact url must be absolute", "urls");
    }
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new ValidationError("contact url must use http or https", "urls");
    }
    const normalized = url.toString();
    if (seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    result.push(normalized);
  }
  return result;
}

export function createContact(input: CreateContactInput): Contact {
  return {
    id: input.id,
    addressBookId: input.addressBookId,
    uid: requireText(input.uid, "uid", MAX_CONTACT_UID_LENGTH),
    displayName: requireText(
      input.displayName,
      "displayName",
      MAX_CONTACT_DISPLAY_NAME_LENGTH,
    ),
    givenName: optionalText(
      input.givenName,
      "givenName",
      MAX_CONTACT_NAME_PART_LENGTH,
    ),
    familyName: optionalText(
      input.familyName,
      "familyName",
      MAX_CONTACT_NAME_PART_LENGTH,
    ),
    nickname: optionalText(
      input.nickname,
      "nickname",
      MAX_CONTACT_NAME_PART_LENGTH,
    ),
    organization: optionalText(
      input.organization,
      "organization",
      MAX_CONTACT_ORGANIZATION_LENGTH,
    ),
    title: optionalText(input.title, "title", MAX_CONTACT_TITLE_LENGTH),
    emails: normalizeEmails(input.emails ?? []),
    phones: normalizePhones(input.phones ?? []),
    postalAddresses: normalizePostalAddresses(input.postalAddresses ?? []),
    urls: normalizeUrls(input.urls ?? []),
    note: optionalText(input.note, "note", MAX_CONTACT_NOTE_LENGTH),
    birthday:
      input.birthday === null || input.birthday === undefined
        ? null
        : createIsoDate(input.birthday, "birthday"),
    // Opaque fidelity payload: passed through verbatim, never trimmed or
    // otherwise interpreted here (see the field doc on `Contact`).
    extraVcardLines: input.extraVcardLines ?? null,
    createdAt: input.createdAt,
    updatedAt: input.updatedAt ?? input.createdAt,
  };
}

export interface UpdateContactInput {
  readonly displayName?: string;
  readonly givenName?: string | null;
  readonly familyName?: string | null;
  readonly nickname?: string | null;
  readonly organization?: string | null;
  readonly title?: string | null;
  readonly emails?: readonly ContactEmailInput[];
  readonly phones?: readonly ContactPhoneInput[];
  readonly postalAddresses?: readonly ContactPostalAddressInput[];
  readonly urls?: readonly string[];
  readonly note?: string | null;
  readonly birthday?: string | null;
  readonly extraVcardLines?: string | null;
}

function toEmailInputs(emails: readonly ContactEmail[]): ContactEmailInput[] {
  return emails.map((email) => ({
    address: email.address,
    label: email.label,
  }));
}

/** Applies a partial edit through the same validation `createContact` uses
 * -- mirrors `updateCalendar` rebuilding via `createCalendar`. An absent
 * field is left untouched; an explicit `null` on a nullable field clears
 * it. */
export function updateContact(
  contact: Contact,
  input: UpdateContactInput,
  updatedAt: string,
): Contact {
  return createContact({
    id: contact.id,
    addressBookId: contact.addressBookId,
    uid: contact.uid,
    displayName: input.displayName ?? contact.displayName,
    givenName:
      input.givenName === undefined ? contact.givenName : input.givenName,
    familyName:
      input.familyName === undefined ? contact.familyName : input.familyName,
    nickname: input.nickname === undefined ? contact.nickname : input.nickname,
    organization:
      input.organization === undefined
        ? contact.organization
        : input.organization,
    title: input.title === undefined ? contact.title : input.title,
    emails: input.emails ?? toEmailInputs(contact.emails),
    phones: input.phones ?? contact.phones,
    postalAddresses: input.postalAddresses ?? contact.postalAddresses,
    urls: input.urls ?? contact.urls,
    note: input.note === undefined ? contact.note : input.note,
    birthday: input.birthday === undefined ? contact.birthday : input.birthday,
    extraVcardLines:
      input.extraVcardLines === undefined
        ? contact.extraVcardLines
        : input.extraVcardLines,
    createdAt: contact.createdAt,
    updatedAt,
  });
}
